### ISSUE TITLE
ocr模型用的哪个 怎么部署呢

### ISSUE THREAD

**Issue by RimsC** [NephrenCake/SealOcr#2]
求解

**Comment by NephrenCake** [comment]
ocr自行查看paddlepaddleocr，需要自己训练以及微调参数

**Comment by RimsC** [comment]
直接用paddleocr的结果就可以吗？paddleocr的结果你做了后处理吧，能给个http请求返回的json合适吗？如果方便可以加下微信号  NirvanaToCrystal  谢谢

**Comment by NephrenCake** [comment]
直接用效果不好。接口已经返回json，你有什么标准自己改就行。

**Comment by RimsC** [comment]
> 直接用效果不好。接口已经返回json，你有什么标准自己改就行。

看懂了  细节我自己再看一下，有效果图可以贴几张吗

**Comment by NephrenCake** [comment]
![image](https://user-images.githubusercontent.com/71604319/177944504-007f3c8a-7a3a-4c3d-b8ae-a00d4a8a8821.png)

**Comment by RimsC** [comment]
> ![image](https://user-images.githubusercontent.com/71604319/177944504-007f3c8a-7a3a-4c3d-b8ae-a00d4a8a8821.png)
> 

印象的图，不好意思，没说清楚😭，印章图片发一下吧，谢谢啦[]()![Screenshot_2022-07-08-15-57-43-586_com.ss.android.lark.ihaier.jpg](https://user-images.githubusercontent.com/10690670/177945520-3e4ddd88-80c5-4676-aef7-d449951041ab.jpg)也可以帮我识别一下这个

**Comment by NephrenCake** [comment]
老早以前的项目了，现在没环境。

**Comment by RimsC** [comment]
> 老早以前的项目了，现在没环境。

谢谢啦，我搞明白流程了，很不错。
